using System.Collections.Generic;
using System.Linq;

namespace ForzaRadioModTool
{
    public static class Strings
    {
        private static readonly Dictionary<string, Dictionary<string, string>> Data =
            new()
        {
            ["EN"] = new()
            {
                ["AppTitle"] = "Forza Radio Mod Tool - v2.0",
                ["DirectorioJuego"] = "Game directory",
                ["BuscarCarpeta"] = "Browse...",
                ["ListaRadios"] = "Radio stations",
                ["CancionesRadio"] = "Songs in station",
                ["ReemplazarCancion"] = "Replace song",
                ["AplicarCambios"] = "Save Changes",
                ["Salir"] = "Exit",
                ["RunFMOD"] = "Extract Bank",
                ["InsertarEnJuego"] = "Insert into Game",
                ["SeleccionaCarpeta"] = "Select the game folder",
                ["NoRadios"] = "No radio stations found.",
                ["ErrorCargar"] = "Error loading data",
                ["NoFMODBanks"] = "FMODBanks folder not found.",
                ["InstrRebuildTitle"] = "Instructions",
                ["InstrRebuildBody"] = "1. Click 'Extract Bank' to extract audio files\n2. Edit audio files as needed\n3. Use FMOD tools to rebuild\n4. Click 'Insert into Game' to apply changes",
                ["CambiosAplicados"] = "Changes applied successfully.",
                ["ErrorGuardar"] = "Error saving file",
                ["NoSePudoAbrirArchivo"] = "Could not open the file",
                ["NoWavParaPreview"] = "WAV file not found for preview.",
                ["SeleccionaNuevoAudio"] = "Select the new audio file",
                ["CancionReemplazadaOk"] = "Song replaced successfully.",
                ["ErrorReemplazarCancion"] = "Error replacing the song",
                ["InstrFMODTitle"] = "Extract songs",
                ["InstrFMODBody"] = "1. Click Extract only\n2. Edit FSB to rename files\n3. Extract again\n4. Close FMOD",
                ["ErrorExtraer"] = "Error extracting",
                ["NoBankBackup"] = "The .bank file was not found in the original or backup folder.",
                ["SeleccionaRadioPrimero"] = "Select a radio first.",
                ["InsertarEnJuegoTitulo"] = "Insert into game",
                ["CopiadosAlJuego"] = "{0} .bank files were copied to the game.",
                ["ErrorCopiandoBank"] = "Error copying {0}",
                ["Play"] = "Play",
                ["ColID"] = "ID",
                ["ColArchivo"] = "File",
                ["ColNombre"] = "Title",
                ["ColArtista"] = "Artist",
                ["Idioma"] = "Language",
                ["Status"] = "Status",
                ["Ready"] = "Ready",
                ["Loading"] = "Loading...",
                ["Processing"] = "Processing...",
                ["Completed"] = "Completed",
                ["Failed"] = "Failed",
            },
            ["MX"] = new Dictionary<string, string>
            {
                ["AppTitle"] = "Forza Radio Mod Tool",
                ["DirectorioJuego"] = "Directorio del juego",
                ["BuscarCarpeta"] = "Buscar...",
                ["ListaRadios"] = "Lista de radios",
                ["CancionesRadio"] = "Canciones de la radio",
                ["ReemplazarCancion"] = "Reemplazar canción",
                ["AplicarCambios"] = "Escribir XML",
                ["Salir"] = "Salir",
                ["RunFMOD"] = "Ejecutar FMOD",
                ["InsertarEnJuego"] = "Insertar canciones en juego",
                ["SeleccionaCarpeta"] = "Selecciona la carpeta del juego",
                ["NoRadios"] = "No se encontraron radios.",
                ["ErrorCargar"] = "Error al cargar datos",
                ["NoFMODBanks"] = "No se encontró la carpeta FMODBanks.",
                ["InstrRebuildTitle"] = "Instrucciones",
                ["InstrRebuildBody"] = "Ejecuta FMOD\nHaz clic en Rebuild\nCierra FMOD",
                ["CambiosAplicados"] = "Cambios aplicados.",
                ["ErrorGuardar"] = "Error al guardar el archivo",
                ["NoSePudoAbrirArchivo"] = "No se pudo abrir el archivo",
                ["NoWavParaPreview"] = "No se encontró el archivo WAV para previsualizar.",
                ["SeleccionaNuevoAudio"] = "Selecciona el nuevo archivo de audio",
                ["CancionReemplazadaOk"] = "Canción reemplazada correctamente.",
                ["ErrorReemplazarCancion"] = "Error al reemplazar la canción",
                ["InstrFMODTitle"] = "Extraer canciones",
                ["InstrFMODBody"] = "Haz clic en Extraer\nEdita el FSB para renombrar archivos\nVuelve a extraer\nCierra FMOD",
                ["ErrorExtraer"] = "Error al extraer",
                ["NoBankBackup"] = "No se encontró el archivo .bank en la carpeta original ni en la de backup.",
                ["SeleccionaRadioPrimero"] = "Selecciona una radio primero.",
                ["InsertarEnJuegoTitulo"] = "Insertar en juego",
                ["CopiadosAlJuego"] = "Se copiaron {0} archivos .bank al juego.",
                ["ErrorCopiandoBank"] = "Error copiando {0}",
                ["Play"] = "Reproducir",
                ["ColID"] = "ID",
                ["ColArchivo"] = "Archivo",
                ["ColNombre"] = "Nombre",
                ["ColArtista"] = "Artista",
                ["Idioma"] = "Idioma",
            },
            ["BR"] = new Dictionary<string, string>
            {
                ["AppTitle"] = "Forza Radio Mod Tool",
                ["DirectorioJuego"] = "Diretório do jogo",
                ["BuscarCarpeta"] = "Procurar...",
                ["ListaRadios"] = "Lista de rádios",
                ["CancionesRadio"] = "Músicas da rádio",
                ["ReemplazarCancion"] = "Substituir música",
                ["AplicarCambios"] = "Gravar XML",
                ["Salir"] = "Sair",
                ["RunFMOD"] = "Executar FMOD",
                ["InsertarEnJuego"] = "Inserir músicas no jogo",
                ["SeleccionaCarpeta"] = "Selecione a pasta do jogo",
                ["NoRadios"] = "Nenhuma rádio encontrada.",
                ["ErrorCargar"] = "Erro ao carregar dados",
                ["NoFMODBanks"] = "Pasta FMODBanks não encontrada.",
                ["InstrRebuildTitle"] = "Instruções",
                ["InstrRebuildBody"] = "Execute o FMOD\nClique em Rebuild\nFeche o FMOD",
                ["CambiosAplicados"] = "Alterações aplicadas.",
                ["ErrorGuardar"] = "Erro ao salvar o arquivo",
                ["NoSePudoAbrirArchivo"] = "Não foi possível abrir o arquivo",
                ["NoWavParaPreview"] = "Arquivo WAV não encontrado para pré-visualização.",
                ["SeleccionaNuevoAudio"] = "Selecione o novo arquivo de áudio",
                ["CancionReemplazadaOk"] = "Música substituída com sucesso.",
                ["ErrorReemplazarCancion"] = "Erro ao substituir a música",
                ["InstrFMODTitle"] = "Extrair músicas",
                ["InstrFMODBody"] = "Clique em Extrair\nEdite o FSB para renomear arquivos\nExtraia novamente\nFeche o FMOD",
                ["ErrorExtraer"] = "Erro ao extrair",
                ["NoBankBackup"] = "O arquivo .bank não foi encontrado na pasta original nem na de backup.",
                ["SeleccionaRadioPrimero"] = "Selecione uma rádio primeiro.",
                ["InsertarEnJuegoTitulo"] = "Inserir no jogo",
                ["CopiadosAlJuego"] = "{0} arquivos .bank foram copiados para o jogo.",
                ["ErrorCopiandoBank"] = "Erro copiando {0}",
                ["Play"] = "Reproduzir",
                ["ColID"] = "ID",
                ["ColArchivo"] = "Arquivo",
                ["ColNombre"] = "Nome",
                ["ColArtista"] = "Artista",
                ["Idioma"] = "Idioma",
            },
            ["DE"] = new Dictionary<string, string>
            {
                ["AppTitle"] = "Forza Radio Mod Tool",
                ["DirectorioJuego"] = "Spielverzeichnis",
                ["BuscarCarpeta"] = "Durchsuchen...",
                ["ListaRadios"] = "Radiosender",
                ["CancionesRadio"] = "Songs im Sender",
                ["ReemplazarCancion"] = "Song ersetzen",
                ["AplicarCambios"] = "XML schreiben",
                ["Salir"] = "Beenden",
                ["RunFMOD"] = "FMOD starten",
                ["InsertarEnJuego"] = "Songs ins Spiel einfügen",
                ["SeleccionaCarpeta"] = "Wähle den Spieleordner",
                ["NoRadios"] = "Keine Radiosender gefunden.",
                ["ErrorCargar"] = "Fehler beim Laden",
                ["NoFMODBanks"] = "Ordner FMODBanks nicht gefunden.",
                ["InstrRebuildTitle"] = "Anweisungen",
                ["InstrRebuildBody"] = "FMOD ausführen\nAuf Rebuild klicken\nFMOD schließen",
                ["CambiosAplicados"] = "Änderungen übernommen.",
                ["ErrorGuardar"] = "Fehler beim Speichern",
                ["NoSePudoAbrirArchivo"] = "Datei konnte nicht geöffnet werden",
                ["NoWavParaPreview"] = "WAV-Datei für Vorschau nicht gefunden.",
                ["SeleccionaNuevoAudio"] = "Neue Audiodatei auswählen",
                ["CancionReemplazadaOk"] = "Song erfolgreich ersetzt.",
                ["ErrorReemplazarCancion"] = "Fehler beim Ersetzen des Songs",
                ["InstrFMODTitle"] = "Songs extrahieren",
                ["InstrFMODBody"] = "Nur auf Extrahieren klicken\nFSB bearbeiten, um Dateien umzubenennen\nErneut extrahieren\nFMOD schließen",
                ["ErrorExtraer"] = "Fehler beim Extrahieren",
                ["NoBankBackup"] = "Die .bank-Datei wurde weder im Original- noch im Backup-Ordner gefunden.",
                ["SeleccionaRadioPrimero"] = "Wähle zuerst einen Sender.",
                ["InsertarEnJuegoTitulo"] = "Ins Spiel einfügen",
                ["CopiadosAlJuego"] = "{0} .bank-Dateien wurden ins Spiel kopiert.",
                ["ErrorCopiandoBank"] = "Fehler beim Kopieren von {0}",
                ["Play"] = "Abspielen",
                ["ColID"] = "ID",
                ["ColArchivo"] = "Datei",
                ["ColNombre"] = "Titel",
                ["ColArtista"] = "Künstler",
                ["Idioma"] = "Sprache",
            },
            ["FR"] = new Dictionary<string, string>
            {
                ["AppTitle"] = "Forza Radio Mod Tool",
                ["DirectorioJuego"] = "Répertoire du jeu",
                ["BuscarCarpeta"] = "Parcourir...",
                ["ListaRadios"] = "Stations de radio",
                ["CancionesRadio"] = "Musiques de la station",
                ["ReemplazarCancion"] = "Remplacer la musique",
                ["AplicarCambios"] = "Écrire XML",
                ["Salir"] = "Quitter",
                ["RunFMOD"] = "Lancer FMOD",
                ["InsertarEnJuego"] = "Insérer les musiques dans le jeu",
                ["SeleccionaCarpeta"] = "Sélectionnez le dossier du jeu",
                ["NoRadios"] = "Aucune station trouvée.",
                ["ErrorCargar"] = "Erreur de chargement",
                ["NoFMODBanks"] = "Dossier FMODBanks introuvable.",
                ["InstrRebuildTitle"] = "Instructions",
                ["InstrRebuildBody"] = "Exécuter FMOD\nCliquer sur Rebuild\nFermer FMOD",
                ["CambiosAplicados"] = "Modifications appliquées.",
                ["ErrorGuardar"] = "Erreur lors de l’enregistrement",
                ["NoSePudoAbrirArchivo"] = "Impossible d’ouvrir le fichier",
                ["NoWavParaPreview"] = "Fichier WAV introuvable pour l’aperçu.",
                ["SeleccionaNuevoAudio"] = "Sélectionnez le nouveau fichier audio",
                ["CancionReemplazadaOk"] = "Musique remplacée avec succès.",
                ["ErrorReemplazarCancion"] = "Erreur lors du remplacement de la musique",
                ["InstrFMODTitle"] = "Extraire les musiques",
                ["InstrFMODBody"] = "Cliquez sur Extraire\nModifiez le FSB pour renommer les fichiers\nExtrayez à nouveau\nFermez FMOD",
                ["ErrorExtraer"] = "Erreur d’extraction",
                ["NoBankBackup"] = "Le fichier .bank est introuvable dans le dossier original ou de sauvegarde.",
                ["SeleccionaRadioPrimero"] = "Sélectionnez d’abord une station.",
                ["InsertarEnJuegoTitulo"] = "Insérer dans le jeu",
                ["CopiadosAlJuego"] = "{0} fichiers .bank ont été copiés dans le jeu.",
                ["ErrorCopiandoBank"] = "Erreur lors de la copie de {0}",
                ["Play"] = "Lire",
                ["ColID"] = "ID",
                ["ColArchivo"] = "Fichier",
                ["ColNombre"] = "Titre",
                ["ColArtista"] = "Artiste",
                ["Idioma"] = "Langue",
            },
        };

        public static string Get(string lang, string key)
        {
            if (string.IsNullOrWhiteSpace(lang)) lang = "EN";
            if (!Data.ContainsKey(lang)) lang = "EN";
            if (Data[lang].TryGetValue(key, out var value)) return value;
            if (Data["EN"].TryGetValue(key, out var enValue)) return enValue;
            return key;
        }
    }
}